export const GET_PROVINCES_START = 'GET_PROVINCES_START';
export const GET_PROVINCES_END = 'API_REQUEST_END';
export const GET_PROVINCES_SUCCESS = 'GET_PROVINCES_SUCCESS';
export const GET_PROVINCES_FAILURE = 'GET_PROVINCES_FAILURE';

export const GET_DISTRICTS_BY_PROVINCES_START = 'GET_DISTRICTS_BY_PROVINCES_START';
export const GET_DISTRICTS_BY_PROVINCES_END = 'GET_DISTRICTS_BY_PROVINCES_END';
export const GET_DISTRICTS_BY_PROVINCES_SUCCESS = 'GET_DISTRICTS_BY_PROVINCES_SUCCESS';
export const GET_DISTRICTS_BY_PROVINCES_FAILURE = 'GET_DISTRICTS_BY_PROVINCES_FAILURE';

export const GET_SECTORS_BY_DISTRICTS_START = 'GET_SECTORS_BY_DISTRICTS_START';
export const GET_SECTORS_BY_DISTRICTS_END = 'GET_SECTORS_BY_DISTRICTS_END';
export const GET_SECTORS_BY_DISTRICTS_SUCCESS = 'GET_SECTORS_BY_DISTRICTS_SUCCESS';
export const GET_SECTORS_BY_DISTRICTS_FAILURE = 'GET_SECTORS_BY_DISTRICTS_FAILURE';

export const GET_CELLS_BY_SECTORS_START = 'GET_CELLS_BY_SECTORS_START';
export const GET_CELLS_BY_SECTORS_END = 'GET_CELLS_BY_SECTORS_END';
export const GET_CELLS_BY_SECTORS_SUCCESS = 'GET_CELLS_BY_SECTORS_SUCCESS';
export const GET_CELLS_BY_SECTORS_FAILURE = 'GET_CELLS_BY_SECTORS_FAILURE';

export const GET_VILLAGE_BY_CELL_START = 'GET_VILLAGE_BY_CELL_START';
export const GET_VILLAGE_BY_CELL_END = 'GET_VILLAGE_BY_CELL_END';
export const GET_VILLAGE_BY_CELL_SUCCESS = 'GET_VILLAGE_BY_CELL_SUCCESS';
export const GET_VILLAGE_BY_CELL_FAILURE = 'GET_VILLAGE_BY_CELL_FAILURE';

export const CREATE_COOPERATIVE_START = 'CREATE_COOPERATIVE_START';
export const CREATE_COOPERATIVE_END = 'CREATE_COOPERATIVE_END';
export const CREATE_COOPERATIVE_SUCCESS = 'CREATE_COOPERATIVE_SUCCESS';
export const CREATE_COOPERATIVE_FAILURE = 'CREATE_COOPERATIVE_FAILURE';

export const GET_COOPERATIVE_START = 'GET_COOPERATIVE_START';
export const GET_COOPERATIVE_END = 'GET_COOPERATIVE_END';
export const GET_COOPERATIVE_SUCCESS = 'GET_COOPERATIVE_SUCCESS';
export const GET_COOPERATIVE_FAILURE = 'GET_COOPERATIVE_FAILURE';

export const GET_ONE_COOPERATIVE_START = 'GET_ONE_COOPERATIVE_START';
export const GET_ONE_COOPERATIVE_END = 'GET_ONE_COOPERATIVE_END';
export const GET_ONE_COOPERATIVE_SUCCESS = 'GET_ONE_COOPERATIVE_SUCCESS';
export const GET_ONE_COOPERATIVE_FAILURE = 'GET_ONE_COOPERATIVE_FAILURE';

export const UPDATE_COOPERATIVE_START = 'UPDATE_COOPERATIVE_START';
export const UPDATE_COOPERATIVE_END = 'UPDATE_COOPERATIVE_END';
export const UPDATE_COOPERATIVE_SUCCESS = 'UPDATE_COOPERATIVE_SUCCESS';
export const UPDATE_COOPERATIVE_FAILURE = 'UPDATE_COOPERATIVE_FAILURE';

export const DELETE_COOPERATIVE_START = 'DELETE_COOPERATIVE_START';
export const DELETE_COOPERATIVE_END = 'DELETE_COOPERATIVE_END';
export const DELETE_COOPERATIVE_SUCCESS = 'DELETE_COOPERATIVE_SUCCESS';
export const DELETE_COOPERATIVE_FAILURE = 'DELETE_COOPERATIVE_FAILURE';


export const CLEAR_DELETE_COOPERATIVE_STORE = 'CLEAR_DELETE_COOPERATIVE_STORE';
export const CLEAR_COOPERATIVE_STORE = 'CLEAR_COOPERATIVE_STORE';