export const GET_PROVINCES_START = 'GET_PROVINCES_START';
export const GET_PROVINCES_END = 'API_REQUEST_END';
export const GET_PROVINCES_SUCCESS = 'GET_PROVINCES_SUCCESS';
export const GET_PROVINCES_FAILURE = 'GET_PROVINCES_FAILURE';

export const GET_DISTRICTS_BY_PROVINCES_START = 'GET_DISTRICTS_BY_PROVINCES_START';
export const GET_DISTRICTS_BY_PROVINCES_END = 'GET_DISTRICTS_BY_PROVINCES_END';
export const GET_DISTRICTS_BY_PROVINCES_SUCCESS = 'GET_DISTRICTS_BY_PROVINCES_SUCCESS';
export const GET_DISTRICTS_BY_PROVINCES_FAILURE = 'GET_DISTRICTS_BY_PROVINCES_FAILURE';

export const GET_SECTORS_BY_DISTRICTS_START = 'GET_SECTORS_BY_DISTRICTS_START';
export const GET_SECTORS_BY_DISTRICTS_END = 'GET_SECTORS_BY_DISTRICTS_END';
export const GET_SECTORS_BY_DISTRICTS_SUCCESS = 'GET_SECTORS_BY_DISTRICTS_SUCCESS';
export const GET_SECTORS_BY_DISTRICTS_FAILURE = 'GET_SECTORS_BY_DISTRICTS_FAILURE';

export const CLEAR_COOPERATIVE_STORE = 'CLEAR_COOPERATIVE_STORE';