export const CREATE_FARMER_START = 'CREATE_FARMER_START';
export const CREATE_FARMER_END = 'CREATE_FARMER_END';
export const CREATE_FARMER_SUCCESS = 'CREATE_FARMER_SUCCESS';
export const CREATE_FARMER_FAILURE = 'CREATE_FARMER_FAILURE';

export const GET_FARMER_START = 'GET_FARMER_START';
export const GET_FARMER_END = 'GET_FARMER_END';
export const GET_FARMER_SUCCESS = 'GET_FARMER_SUCCESS';
export const GET_FARMER_FAILURE = 'GET_FARMER_FAILURE';

export const GET_ZONE_START = 'GET_ZONE_START';
export const GET_ZONE_END = 'GET_ZONE_END';
export const GET_ZONE_SUCCESS = 'GET_ZONE_SUCCESS';
export const GET_ZONE_AILURE = 'GET_ZONE_FAILURE';

export const DELETE_FARMER_START = 'DELETE_FARMER_START';
export const DELETE_FARMER_END = 'DELETE_FARMER_END';
export const DELETE_FARMER_SUCCESS = 'DELETE_FARMER_SUCCESS';
export const DELETE_FARMER_AILURE = 'DELETE_FARMER_FAILURE';

export const GET_ONE_FARMER_START = 'GET_ONE_FARMER_START';
export const GET_ONE_FARMER_END = 'GET_ONE_FARMER_END';
export const GET_ONE_FARMER_SUCCESS = 'GET_ONE_FARMER_SUCCESS';
export const GET_ONE_FARMER_FAILURE = 'GET_ONE_FARMER_FAILURE';

export const CLEAR_FARMER_STORE = 'CLEAR_FARMER_STORE';