export const CREATE_FARMER_START = 'CREATE_FARMER_START';
export const CREATE_FARMER_END = 'CREATE_FARMER_END';
export const CREATE_FARMER_SUCCESS = 'CREATE_FARMER_SUCCESS';
export const CREATE_FARMER_FAILURE = 'CREATE_FARMER_FAILURE';

export const GET_FARMER_START = 'GET_FARMER_START';
export const GET_FARMER_END = 'GET_FARMER_END';
export const GET_FARMER_SUCCESS = 'GET_FARMER_SUCCESS';
export const GET_FARMER_FAILURE = 'GET_FARMER_FAILURE';


export const CLEAR_FARMER_STORE = 'CLEAR_FARMER_STORE';