
export const GET_ORGANIZATION_START = 'GET_ORGANIZATION_START';
export const GET_ORGANIZATION_END = 'GET_ORGANIZATION_END';
export const GET_ORGANIZATION_SUCCESS = 'GET_ORGANIZATION_SUCCESS';
export const GET_ORGANIZATION_FAILURE = 'GET_ORGANIZATION_FAILURE';

export const GET_ZONE_BY_COOPERATIVE_START = 'GET_ZONE_BY_COOPERATIVE_START';
export const GET_ZONE_BY_COOPERATIVE_END = 'GET_ZONE_BY_COOPERATIVE_END';
export const GET_ZONE_BY_COOPERATIVE_SUCCESS = 'GET_ZONE_BY_COOPERATIVE_SUCCESS';
export const GET_ZONE_BY_COOPERATIVE_FAILURE = 'GET_ZONE_BY_COOPERATIVE_FAILURE';

export const GET_SITE_BY_ZONE_START = 'GET_SITE_BY_ZONE_START';
export const GET_SITE_BY_ZONE_END = 'GET_SITE_BY_ZONE_END';
export const GET_SITE_BY_ZONE_SUCCESS = 'GET_SITE_BY_ZONE_SUCCESS';
export const GET_SITE_BY_ZONE_FAILURE = 'GET_SITE_BY_ZONE_FAILURE';
